# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#ff99a8" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#ff4b66", bold = true, italic = true, underline = true }
find_position = { fg = "#f84555", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ff7a91", bg = "#ff7a91" }
marker_cut      = { fg = "#e04f5f", bg = "#e04f5f" }
marker_marked   = { fg = "#f84555", bg = "#f84555" }
marker_selected = { fg = "#ff4b66", bg = "#ff4b66" }

# Count
count_copied   = { fg = "#1e1e2e", bg = "#ff7a91" }
count_cut      = { fg = "#1e1e2e", bg = "#e04f5f" }
count_selected = { fg = "#1e1e2e", bg = "#ff4b66" }

# Border
border_symbol = "│"
border_style  = { fg = "#d73442" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#1e1e2e", bg = "#ff5c7a", bold = true }
inactive = { fg = "#ff5c7a", bg = "#313244" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#1e1e2e", bg = "#ff5c7a", bold = true }
normal_alt  = { fg = "#ff5c7a", bg = "#313244" }

# Select mode
select_main = { fg = "#1e1e2e", bg = "#ff7a91", bold = true }
select_alt  = { fg = "#ff7a91", bg = "#313244" }

# Unset mode
unset_main = { fg = "#1e1e2e", bg = "#ffb3b3", bold = true }
unset_alt  = { fg = "#ffb3b3", bg = "#313244" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#d73442" }
perm_type  = { fg = "#ff5c7a" }
perm_read  = { fg = "#ff4b66" }
perm_write = { fg = "#e04f5f" }
perm_exec  = { fg = "#ff7a91" }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#ff5c7a", bg = "#45475a" }
progress_error  = { fg = "#ff4b66", bg = "#e04f5f" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#ff5c7a" }
active   = { fg = "#ff99a8", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#ff5c7a" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#ff5c7a" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#ff5c7a" }
title   = {}
hovered = { fg = "#ff99a8", bold = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#313244" }
cand            = { fg = "#f84555" }
rest            = { fg = "#ff99a8" }
desc            = { fg = "#ff99a8" }
separator       = "  "
separator_style = { fg = "#585b70" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#f84555" }
run     = { fg = "#ff99a8" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#313244", bg = "#ffb3b3" }

# : }}}


# : Spotter {{{

[spot]
border   = { fg = "#ff5c7a" }
title    = { fg = "#ff5c7a" }
tbl_col  = { fg = "#f84555" }
tbl_cell = { fg = "#ff99a8", bg = "#45475a" }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#ff7a91" }
title_warn  = { fg = "#ff4b66" }
title_error = { fg = "#e04f5f" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Image
	{ mime = "image/*", fg = "#f84555" },
	# Media
	{ mime = "{audio,video}/*", fg = "#ff4b66" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ff99a8" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#ff7a91" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#9399b2" },
	# Fallback
	{ url = "*", fg = "#ffb3b3" },
	{ url = "*/", fg = "#ff5c7a" },
	{ name = "*", fg = "#ffb3b3" },
	{ name = "*/", fg = "#ff5c7a" }
]

# : }}}
