set -g @sw_bg        "#0d0303"
set -g @sw_fg        "#ffeeee"

set -g @sw_rosewater "#ffdddd"
set -g @sw_flamingo  "#ffb3c1"
set -g @sw_pink      "#ff1493"
set -g @sw_mauve     "#cf1d82"
set -g @sw_red       "#ff0033"
set -g @sw_maroon    "#911d29"
set -g @sw_peach     "#ff0066"
set -g @sw_yellow    "#deba1b"
set -g @sw_green     "#31e619"
set -g @sw_teal      "#56c6e8"
set -g @sw_sky       "#00ccff"
set -g @sw_sapphire  "#161ddb"
set -g @sw_blue      "#80a0ff"
set -g @sw_lavender  "#ff0080"

set -g @sw_subtext_1 "#ff99aa"
set -g @sw_subtext_0 "#c2185b"
set -g @sw_overlay_2 "#e01b50"
set -g @sw_overlay_1 "#911d29"
set -g @sw_overlay_0 "#591118"
set -g @sw_surface_2 "#440011"
set -g @sw_surface_1 "#330011"
set -g @sw_surface_0 "#220000"
set -g @sw_mantle    "#110000"
set -g @sw_crust     "#000000"
