set -g @sw_bg        "#1d0b26"
set -g @sw_fg        "#ffeeff"

set -g @sw_rosewater "#ffddff"
set -g @sw_flamingo  "#ffbbff"
set -g @sw_pink      "#ff1dce"
set -g @sw_mauve     "#cc00ff"
set -g @sw_red       "#ff0066"
set -g @sw_maroon    "#e01b50"
set -g @sw_peach     "#ff1493"
set -g @sw_yellow    "#deba1b"
set -g @sw_green     "#31e619"
set -g @sw_teal      "#56c6e8"
set -g @sw_sky       "#00ccff"
set -g @sw_sapphire  "#161ddb"
set -g @sw_blue      "#80a0ff"
set -g @sw_lavender  "#bb00ff"

set -g @sw_subtext_1 "#ddbbff"
set -g @sw_subtext_0 "#bca4dd"
set -g @sw_overlay_2 "#cc33ff"
set -g @sw_overlay_1 "#962f8b"
set -g @sw_overlay_0 "#591155"
set -g @sw_surface_2 "#441166"
set -g @sw_surface_1 "#330333"
set -g @sw_surface_0 "#220044"
set -g @sw_mantle    "#11071a"
set -g @sw_crust     "#000000"
