# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#b3a0d5" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#d2a1f1", bold = true, italic = true, underline = true }
find_position = { fg = "#d8a9ff", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#9b69e4", bg = "#9b69e4" }
marker_cut      = { fg = "#d17ae1", bg = "#d17ae1" }
marker_marked   = { fg = "#b3a0d5", bg = "#b3a0d5" }
marker_selected = { fg = "#d2a1f1", bg = "#d2a1f1" }

# Count
count_copied   = { fg = "#1e1e2e", bg = "#9b69e4" }
count_cut      = { fg = "#1e1e2e", bg = "#d17ae1" }
count_selected = { fg = "#1e1e2e", bg = "#d2a1f1" }

# Border
border_symbol = "│"
border_style  = { fg = "#7f4d90" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#1e1e2e", bg = "#9a62d6", bold = true }
inactive = { fg = "#9a62d6", bg = "#4e2d4d" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#1e1e2e", bg = "#9a62d6", bold = true }
normal_alt  = { fg = "#9a62d6", bg = "#4e2d4d" }

# Select mode
select_main = { fg = "#1e1e2e", bg = "#9b69e4", bold = true }
select_alt  = { fg = "#9b69e4", bg = "#4e2d4d" }

# Unset mode
unset_main = { fg = "#1e1e2e", bg = "#e2a1d1", bold = true }
unset_alt  = { fg = "#e2a1d1", bg = "#4e2d4d" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#7f4d90" }
perm_type  = { fg = "#9a62d6" }
perm_read  = { fg = "#d2a1f1" }
perm_write = { fg = "#d17ae1" }
perm_exec  = { fg = "#9b69e4" }

# Progress
progress_label  = { fg = "#e8d9ff", bold = true }
progress_normal = { fg = "#9a62d6", bg = "#5e3c5d" }
progress_error  = { fg = "#d2a1f1", bg = "#d17ae1" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#9a62d6" }
active   = { fg = "#d8a9ff", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#9a62d6" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#9a62d6" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#9a62d6" }
title   = {}
hovered = { fg = "#d8a9ff", bold = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#4e2d4d" }
cand            = { fg = "#b3a0d5" }
rest            = { fg = "#9a84c5" }
desc            = { fg = "#d8a9ff" }
separator       = "  "
separator_style = { fg = "#8a6a9f" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#b3a0d5" }
run     = { fg = "#d8a9ff" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#4e2d4d", bg = "#d3b9f2" }

# : }}}


# : Spotter {{{

[spot]
border   = { fg = "#9a62d6" }
title    = { fg = "#9a62d6" }
tbl_col  = { fg = "#b3a0d5" }
tbl_cell = { fg = "#d8a9ff", bg = "#5e3c5d" }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#9b69e4" }
title_warn  = { fg = "#d2a1f1" }
title_error = { fg = "#d17ae1" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Image
	{ mime = "image/*", fg = "#b3a0d5" },
	# Media
	{ mime = "{audio,video}/*", fg = "#d2a1f1" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#d8a9ff" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#9b69e4" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#9a84c5" },
	# Fallback
	{ url = "*", fg = "#d3b9f2" },
	{ url = "*/", fg = "#9a62d6" },
	{ name = "*", fg = "#d3b9f2" },
	{ name = "*/", fg = "#9a62d6" }
]

# : }}}
